name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

env:
  DOTNET_VERSION: '5.0.100'
  DOTNET_3.0_VERSION: '3.1.301'
  AZURE_FUNCTIONAPP_NAME: 'LuasAPIFunction'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './LuasAPI.AzureFunction'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_3_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  pack:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_3_VERSION }}
    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=${{ github.event.release.tag_name }}
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./artifacts

  publish-to-nuget:
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name == 'release' && !github.event.release.draft
    steps:
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - name: Upload Asset to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: artifacts/LuasAPI.NET.${{ github.event.release.tag_name }}.nupkg
        asset_name: artifacts/LuasAPI.NET.${{ github.event.release.tag_name }}.nupkg
        asset_content_type: application/zip
    - name: Publish packages
      run: dotnet nuget push ./artifacts/**.nupkg --source nuget.org --api-key ${{secrets.NUGET_API_KEY}}

  deploy-azure-function:
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name == 'release' && !github.event.release.prerelease && !github.event.release.draft
    steps:
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - name: 'Run Dotnet API Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

